WHENEVER SQLERROR EXIT SQL.SQLCODE
SET VERIFY OFF
ACCEPT app_password CHAR PROMPT 'New SMART_CLOSET password: ' HIDE
CREATE USER smart_closet IDENTIFIED BY "&app_password";
GRANT CREATE SESSION, CREATE TABLE TO smart_closet;
ALTER USER smart_closet QUOTA 200M ON USERS;
PROMPT SMART_CLOSET user created in XEPDB1.
EXIT
