WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE clothes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category NVARCHAR2(40) NOT NULL,
    color NVARCHAR2(40) NOT NULL,
    season NVARCHAR2(40) NOT NULL,
    is_favorite NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_favorite IN (0, 1)),
    import_key VARCHAR2(120) UNIQUE,
    image_mime VARCHAR2(80) NOT NULL,
    image_data BLOB NOT NULL
);

CREATE TABLE coordination (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name NVARCHAR2(120) NOT NULL,
    is_favorite NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_favorite IN (0, 1)),
    import_key VARCHAR2(120) UNIQUE
);

CREATE TABLE coordination_item (
    coordination_id NUMBER NOT NULL,
    clothes_id NUMBER NOT NULL,
    display_order NUMBER NOT NULL,
    CONSTRAINT coordination_item_pk PRIMARY KEY (coordination_id, clothes_id),
    CONSTRAINT coordination_item_coord_fk FOREIGN KEY (coordination_id)
        REFERENCES coordination(id) ON DELETE CASCADE,
    CONSTRAINT coordination_item_clothes_fk FOREIGN KEY (clothes_id)
        REFERENCES clothes(id) ON DELETE CASCADE,
    CONSTRAINT coordination_item_order_uk UNIQUE (coordination_id, display_order)
);

CREATE INDEX coordination_item_clothes_ix ON coordination_item(clothes_id);
PROMPT Smart Closet tables created.
EXIT
